"""
Django settings for base_relaction project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
import logging
from pathlib import Path
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
LANGUAGE_CODE = "ru-RU"
AUTH_USER_MODEL = "recreation.CustomUser"


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-+o)%wo9aq84zi9p@n3w-o(i$5q)76(t%*w6xoqkf@d#5vunr+1"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ALLOWED_HOSTS = ['*', 'idly-shading-matador.ngrok-free.dev']
CSRF_TRUSTED_ORIGINS = ['https://idly-shading-matador.ngrok-free.dev']

YOOKASSA_SHOP_ID = '1356724'
YOOKASSA_SECRET_KEY = 'test_Dwwl-NBjGpB7OLZzJlwx9h1bxkhJc3wfmGBM6Np-taA'


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "debug_toolbar",
    "django_filters",
    "simple_history",
    "recreation.apps.RecreationConfig",
    "rest_framework",
    "ckeditor",
    "import_export",
]

REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
    ],
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    'whitenoise.middleware.WhiteNoiseMiddleware',
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "debug_toolbar.middleware.DebugToolbarMiddleware",
]

INTERNAL_IPS = ["127.0.0.1"]

ROOT_URLCONF = "base_relaction.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "templates",
            os.path.join(BASE_DIR, "recreation/templates/registration"),
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                # "recreation.context_processors.password_settings",
            ],
        },
    },
]

WSGI_APPLICATION = "base_relaction.wsgi.application"
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     }
# }
DATABASES = {
    'default': dj_database_url.config(
        default='postgresql://postgres:postgres@localhost:5432/base_relaction',
        conn_max_age=600,
        ssl_require=True
    )
}


# Переопределение для Docker
if os.environ.get("DOCKER_CONTAINER"):
    DATABASES["default"] = dj_database_url.config(
        default="postgres://postgres:postgres@db:5432/base_relaction", conn_max_age=600
    )
# Password validation https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators
MIN_LEGTH_PASSWORD_CONSTANT = 8

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator", 
        "OPTIONS": {
             "min_length": MIN_LEGTH_PASSWORD_CONSTANT,
        }
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization https://docs.djangoproject.com/en/5.1/topics/i18n/

TIME_ZONE = "UTC"

USE_I18N = True
USE_L10N = True

# Static files (CSS, JavaScript, Images) https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static"), BASE_DIR / "static"]
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
# Default primary key field type https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGIN_REDIRECT_URL = "/admin/"
LOGIN_REDIRECT_URL = "/account/"
LOGOUT_REDIRECT_URL = "home"
LOGIN_URL = "/login/"

SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"

AUTHENTICATION_BACKENDS = [
    "recreation.backends.EmailPhoneBackend",
    "django.contrib.auth.backends.ModelBackend",  # Оставляем стандартный бэкенд
]
CKEDITOR_BASEPATH = "/static/ckeditor/ckeditor/"
CKEDITOR_CONFIGS = {
    "default": {
        "toolbar": [
            "heading",
            "|",
            "bold",
            "italic",
            "link",
            "bulletedList",
            "numberedList",
            "blockQuote",
        ],
        "height": 300,
        "width": "100%",
    },
}

TRANSLATABLE_MODEL_MODULES = [
    "yourapp.models",  # Укажите путь к вашим моделям, например 'main.models'
]

# Настройки ЮKassa
YOOKASSA_SHOP_ID = '1356724'
YOOKASSA_SECRET_KEY = 'test_Dwwl-NBjGpB7OLZzJlwx9h1bxkhJc3wfmGBM6Np-taA'
YOOKASSA_RETURN_URL = 'http://idly-shading-matador.ngrok-free.dev/payment/success/'

# Настройки бронирования
BOOKING_PREPAYMENT_PERCENT = 30  # 30% предоплата
BOOKING_REFUND_DAYS = 3  # Возврат при отмене за 3+ дней

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

logger = logging.getLogger('django.db.backends')
logger.setLevel(logging.DEBUG)
logger.addHandler(logging.StreamHandler())


# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# Яндекс почта
EMAIL_HOST = 'smtp.yandex.ru'
EMAIL_PORT = 465
EMAIL_USE_SSL = True
EMAIL_USE_TLS = False
EMAIL_HOST_USER = 'dzvaaas@yandex.ru'  # Ваш Яндекс email
EMAIL_HOST_PASSWORD = 'dbodekwhfgvcogpa'  # Пароль приложения (см. инструкцию ниже)
DEFAULT_FROM_EMAIL = 'База отдыха "Ёлки" <dzvaaas@yandex.ru>'
SERVER_EMAIL = 'dzvaaas@yandex.ru'  # Для ошибок

# Получатели ошибок (админы)
ADMINS = [
    ('Admin', 'dzvaaas@yandex.ru'),
    # Можно добавить дополнительные email
    # ('Manager', 'manager@yolki.ru'),
]

# # Настройки для разработки/продакшена
# if DEBUG:
#     EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# else:
#     EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# Дополнительные настройки email
EMAIL_TIMEOUT = 30  # Таймаут в секундах
EMAIL_USE_SSL = False  # Для Яндекс используем TLS, не SSL

# Настройки для улучшения доставки
EMAIL_SUBJECT_PREFIX = '[Ёлки] '  # Префикс для всех писем

# Настройки кодировки
DEFAULT_CHARSET = 'utf-8'

# ALLOWED_HOSTS = ['*', 'idly-shading-matador.ngrok-free.dev']  # или конкретно '.ngrok-free.dev', 'localhost', '127.0.0.1']
# CSRF_TRUSTED_ORIGINS = ['https://idly-shading-matador.ngrok-free.dev']

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')