# Generated by Django 4.2.23 on 2025-11-20 18:29

import ckeditor.fields
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="Формат: +79999999999",
                        max_length=20,
                        unique=True,
                        verbose_name="Телефон",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email address"
                    ),
                ),
                ("last_name", models.CharField(max_length=100, verbose_name="Фамилия")),
                ("first_name", models.CharField(max_length=100, verbose_name="Имя")),
                (
                    "patronymic",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Отчество"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
                "db_table": "recreation_customuser",
                "ordering": ["last_name", "first_name"],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "booking_id",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID бронирования",
                    ),
                ),
                ("check_in_date", models.DateField(verbose_name="Дата заезда")),
                ("check_out_date", models.DateField(verbose_name="Дата выезда")),
                (
                    "guests",
                    models.PositiveIntegerField(verbose_name="Количество гостей"),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=20, verbose_name="Телефон"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "client_name",
                    models.CharField(
                        default="Не указано", max_length=255, verbose_name="Имя клиента"
                    ),
                ),
                (
                    "base_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Базовая стоимость",
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Общая стоимость",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "comment",
                    ckeditor.fields.RichTextField(
                        blank=True, null=True, verbose_name="Комментарий"
                    ),
                ),
            ],
            options={
                "verbose_name": "Бронирование",
                "verbose_name_plural": "Бронирования",
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "client_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID клиента"
                    ),
                ),
                ("last_name", models.CharField(max_length=100, verbose_name="Фамилия")),
                ("first_name", models.CharField(max_length=100, verbose_name="Имя")),
                (
                    "patronymic",
                    models.CharField(max_length=100, verbose_name="Отчество"),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=20, verbose_name="Номер телефона"),
                ),
                ("email", models.EmailField(max_length=255, verbose_name="Email")),
                (
                    "document",
                    models.FileField(
                        blank=True,
                        help_text="Загрузите сканы документов (паспорт, водительские права и т.д.)",
                        null=True,
                        upload_to="client_documents/%Y/%m/%d/",
                        verbose_name="Документ",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Учетная запись",
                    ),
                ),
            ],
            options={
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "employee_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID сотрудника"
                    ),
                ),
                ("last_name", models.CharField(max_length=100, verbose_name="Фамилия")),
                ("first_name", models.CharField(max_length=100, verbose_name="Имя")),
                (
                    "patronymic",
                    models.CharField(max_length=100, verbose_name="Отчество"),
                ),
                (
                    "contact_info",
                    models.CharField(
                        max_length=255, verbose_name="Контактная информация"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Телефон"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "hire_date",
                    models.DateField(blank=True, null=True, verbose_name="Дата приема"),
                ),
            ],
            options={
                "verbose_name": "Сотрудник",
                "verbose_name_plural": "Сотрудники",
            },
        ),
        migrations.CreateModel(
            name="House",
            fields=[
                (
                    "house_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID дома"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название коттеджа"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=100,
                        unique=True,
                        verbose_name="URL-идентификатор",
                    ),
                ),
                (
                    "location",
                    models.CharField(max_length=200, verbose_name="Местоположение"),
                ),
                ("capacity", models.IntegerField(verbose_name="Вместимость (чел.)")),
                (
                    "price_per_night",
                    models.IntegerField(verbose_name="Цена за ночь (руб.)"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "amenities",
                    models.TextField(blank=True, null=True, verbose_name="Удобства"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="houses/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "employee_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="recreation.employee",
                        verbose_name="Ответственный сотрудник",
                    ),
                ),
            ],
            options={
                "verbose_name": "Коттедж",
                "verbose_name_plural": "Коттеджи",
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "position_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID должности"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название должности"),
                ),
                (
                    "responsibilities",
                    ckeditor.fields.RichTextField(verbose_name="Обязанности"),
                ),
            ],
            options={
                "verbose_name": "Должность",
                "verbose_name_plural": "Должности",
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250, verbose_name="Заголовок")),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=250,
                        unique=True,
                        unique_for_date="publish",
                        verbose_name="URL-адрес",
                    ),
                ),
                ("body", ckeditor.fields.RichTextField(verbose_name="Содержание")),
                (
                    "publish",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Дата публикации",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Черновик"), ("published", "Опубликовано")],
                        default="draft",
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="post_images/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blog_posts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пост",
                "verbose_name_plural": "Посты",
                "ordering": ["-publish"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "service_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID услуги"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название услуги"),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена"
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="Количество")),
                (
                    "image",
                    models.ImageField(
                        upload_to="services/", verbose_name="Изображение"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("entertainment", "Развлечения"),
                            ("relax", "Релакс"),
                            ("transport", "Транспорт"),
                            ("other", "Другое"),
                        ],
                        max_length=20,
                        verbose_name="Тип услуги",
                    ),
                ),
            ],
            options={
                "verbose_name": "Услуга",
                "verbose_name_plural": "Услуги",
                "ordering": ["type", "name"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Название тега")),
            ],
            options={
                "verbose_name": "Тег",
                "verbose_name_plural": "Теги",
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "review_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID отзыва"
                    ),
                ),
                ("rating", models.IntegerField(verbose_name="Рейтинг")),
                ("comment", ckeditor.fields.RichTextField(verbose_name="Комментарий")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "client_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recreation.client",
                        verbose_name="Клиент",
                    ),
                ),
                (
                    "house_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recreation.house",
                        verbose_name="Коттедж",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PostTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recreation.post",
                        verbose_name="Пост",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recreation.tag",
                        verbose_name="Тег",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тег поста",
                "verbose_name_plural": "Теги постов",
            },
        ),
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="posts",
                through="recreation.PostTag",
                to="recreation.tag",
                verbose_name="Теги",
            ),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID платежа"
                    ),
                ),
                (
                    "yookassa_payment_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="ID платежа ЮKassa",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Сумма"
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("full", "Полная оплата"),
                            ("prepayment", "Предоплата"),
                        ],
                        max_length=20,
                        verbose_name="Тип оплаты",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает оплаты"),
                            ("succeeded", "Оплачено"),
                            ("canceled", "Отменено"),
                            ("waiting_for_capture", "Ожидает подтверждения"),
                            ("refunded", "Возвращено"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "payment_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "captured_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата подтверждения"
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recreation.booking",
                        verbose_name="Бронирование",
                    ),
                ),
            ],
            options={
                "verbose_name": "Платеж",
                "verbose_name_plural": "Платежи",
                "ordering": ["-payment_date"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalHouse",
            fields=[
                (
                    "house_id",
                    models.IntegerField(
                        blank=True, db_index=True, verbose_name="ID дома"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название коттеджа"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=100, verbose_name="URL-идентификатор"
                    ),
                ),
                (
                    "location",
                    models.CharField(max_length=200, verbose_name="Местоположение"),
                ),
                ("capacity", models.IntegerField(verbose_name="Вместимость (чел.)")),
                (
                    "price_per_night",
                    models.IntegerField(verbose_name="Цена за ночь (руб.)"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "amenities",
                    models.TextField(blank=True, null=True, verbose_name="Удобства"),
                ),
                (
                    "image",
                    models.TextField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "employee_id",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="recreation.employee",
                        verbose_name="Ответственный сотрудник",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Коттедж",
                "verbose_name_plural": "historical Коттеджи",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalBooking",
            fields=[
                (
                    "booking_id",
                    models.IntegerField(
                        blank=True, db_index=True, verbose_name="ID бронирования"
                    ),
                ),
                ("check_in_date", models.DateField(verbose_name="Дата заезда")),
                ("check_out_date", models.DateField(verbose_name="Дата выезда")),
                (
                    "guests",
                    models.PositiveIntegerField(verbose_name="Количество гостей"),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=20, verbose_name="Телефон"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "client_name",
                    models.CharField(
                        default="Не указано", max_length=255, verbose_name="Имя клиента"
                    ),
                ),
                (
                    "base_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Базовая стоимость",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Дата создания"
                    ),
                ),
                (
                    "comment",
                    ckeditor.fields.RichTextField(
                        blank=True, null=True, verbose_name="Комментарий"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "client_id",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="recreation.client",
                        verbose_name="Клиент",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "house",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="recreation.house",
                        verbose_name="Коттедж",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Бронирование",
                "verbose_name_plural": "historical Бронирования",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Facility",
            fields=[
                (
                    "facility_id",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID оборудования",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "location",
                    models.CharField(max_length=100, verbose_name="Расположение"),
                ),
                ("description", ckeditor.fields.RichTextField(verbose_name="Описание")),
                ("status", models.CharField(max_length=50, verbose_name="Статус")),
                (
                    "house_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recreation.house",
                        verbose_name="Коттедж",
                    ),
                ),
            ],
            options={
                "verbose_name": "Оборудование",
                "verbose_name_plural": "Оборудование",
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "event_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID мероприятия"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("date", models.DateField(verbose_name="Дата")),
                (
                    "location",
                    ckeditor.fields.RichTextField(verbose_name="Место проведения"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="event_images/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "event_url",
                    models.URLField(blank=True, verbose_name="Ссылка на мероприятие"),
                ),
                (
                    "booking_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="recreation.booking",
                        verbose_name="Бронирование",
                    ),
                ),
            ],
            options={
                "verbose_name": "Мероприятие",
                "verbose_name_plural": "Мероприятия",
            },
        ),
        migrations.AddField(
            model_name="employee",
            name="position_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="recreation.position",
                verbose_name="Должность",
            ),
        ),
        migrations.CreateModel(
            name="BookingService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("booking_date", models.DateField(verbose_name="Дата бронирования")),
                ("return_date", models.DateField(verbose_name="Дата возврата")),
                (
                    "booking_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recreation.booking",
                        verbose_name="Бронирование",
                    ),
                ),
                (
                    "service_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recreation.service",
                        verbose_name="Услуга",
                    ),
                ),
            ],
            options={
                "verbose_name": "Бронирование услуги",
                "verbose_name_plural": "Бронирования услуг",
            },
        ),
        migrations.AddField(
            model_name="booking",
            name="client_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="recreation.client",
                verbose_name="Клиент",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="house",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="recreation.house",
                verbose_name="Коттедж",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="services",
            field=models.ManyToManyField(
                blank=True,
                to="recreation.service",
                verbose_name="Дополнительные услуги",
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["-publish"], name="recreation__publish_27e44d_idx"
            ),
        ),
    ]
