# Generated by Django 4.2.23 on 2025-11-20 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recreation", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
    ]
