# Generated by Django 4.2.23 on 2025-11-22 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recreation", "0002_alter_customuser_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="body",
            field=models.TextField(verbose_name="Содержание"),
        ),
        migrations.CreateModel(
            name="HouseImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="houses/gallery/%Y/%m/%d/", verbose_name="Изображение"
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Подпись"
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Порядок")),
                (
                    "is_main",
                    models.BooleanField(
                        default=False, verbose_name="Главное изображение"
                    ),
                ),
                (
                    "house",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="recreation.house",
                        verbose_name="Коттедж",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение коттеджа",
                "verbose_name_plural": "Изображения коттеджей",
                "ordering": ["order", "id"],
            },
        ),
    ]
