# Generated by Django 4.2.23 on 2025-11-25 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recreation", "0003_add_houseimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="TravelPackage",
            fields=[
                ("package_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Название пакета"),
                ),
                (
                    "package_type",
                    models.CharField(
                        choices=[
                            ("weekend", "Выходные"),
                            ("holiday", "Праздничный"),
                            ("weekday", "Будничный"),
                            ("extended", "Продленный"),
                            ("custom", "Индивидуальный"),
                        ],
                        max_length=20,
                        verbose_name="Тип пакета",
                    ),
                ),
                (
                    "duration_days",
                    models.IntegerField(verbose_name="Длительность (дней)"),
                ),
                ("min_guests", models.IntegerField(verbose_name="Мин. гостей")),
                ("max_guests", models.IntegerField(verbose_name="Макс. гостей")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Базовая цена"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="packages/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "local_discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Скидка для местных (%)",
                    ),
                ),
                (
                    "quick_booking",
                    models.BooleanField(
                        default=False, verbose_name="Быстрое бронирование"
                    ),
                ),
                (
                    "flexible_checkin",
                    models.BooleanField(default=False, verbose_name="Гибкий заезд"),
                ),
                (
                    "base_house",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recreation.house",
                        verbose_name="Базовый коттедж",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пакет путешествия",
                "verbose_name_plural": "Пакеты путешествий",
                "db_table": "recreation_travelpackage",
            },
        ),
        migrations.CreateModel(
            name="PackageService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1, verbose_name="Количество")),
                (
                    "included_in_base",
                    models.BooleanField(
                        default=True, verbose_name="Включено в базовую стоимость"
                    ),
                ),
                (
                    "optional",
                    models.BooleanField(
                        default=False, verbose_name="Опциональная услуга"
                    ),
                ),
                (
                    "price_override",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Спец. цена",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recreation.travelpackage",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recreation.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Услуга в пакете",
                "verbose_name_plural": "Услуги в пакетах",
                "db_table": "recreation_packageservice",
            },
        ),
        migrations.CreateModel(
            name="PackageOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Название опции"),
                ),
                (
                    "option_type",
                    models.CharField(
                        choices=[
                            ("food", "Питание"),
                            ("activities", "Активности"),
                            ("comfort", "Комфорт"),
                            ("entertainment", "Развлечения"),
                            ("local", "Локальные услуги"),
                        ],
                        max_length=20,
                        verbose_name="Тип опции",
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "popular_local",
                    models.BooleanField(
                        default=False, verbose_name="Популярно у местных"
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="recreation.travelpackage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Опция пакета",
                "verbose_name_plural": "Опции пакетов",
                "db_table": "recreation_packageoption",
            },
        ),
        migrations.CreateModel(
            name="CustomPackageBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "custom_requests",
                    models.TextField(blank=True, verbose_name="Особые пожелания"),
                ),
                (
                    "total_package_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Общая стоимость пакета",
                    ),
                ),
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recreation.booking",
                        verbose_name="Бронирование",
                    ),
                ),
                (
                    "selected_options",
                    models.ManyToManyField(
                        blank=True,
                        to="recreation.packageoption",
                        verbose_name="Выбранные опции",
                    ),
                ),
                (
                    "travel_package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recreation.travelpackage",
                        verbose_name="Пакет",
                    ),
                ),
            ],
            options={
                "verbose_name": "Бронирование пакета",
                "verbose_name_plural": "Бронирования пакетов",
                "db_table": "recreation_custompackagebooking",
            },
        ),
    ]
