# Generated by Django 4.2.23 on 2025-11-25 20:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("recreation", "0004_travelpackage_packageservice_packageoption_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="custompackagebooking",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Бронирование пакета",
                "verbose_name_plural": "Бронирования пакетов",
            },
        ),
        migrations.AddField(
            model_name="custompackagebooking",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Дата создания",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="custompackagebooking",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
        migrations.AlterField(
            model_name="custompackagebooking",
            name="booking",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="custom_package",
                to="recreation.booking",
                verbose_name="Бронирование",
            ),
        ),
    ]
